kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
  template:
    metadata:
      labels:
        app: java-quarkus-app
    spec:
      containers:
        - name: my-java-quarkus
          image: java-quarkus-image:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-java-quarkus-svc
spec:
ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
selector:
  app: java-quarkus-app